wbt_car: 0.1
camera:
  front: 4
  side: 3
io:
  left_sensor: 8
  right_sensor: 7
  key: 1
  light: 2
speed:
  x:
    limit: 0.7
  y:
    limit: 0.7
  angle:
    limit: 3

# 巡航pid
lane_pid:
  cfg_pid_y:
    Kp: 1 #10
    Ki: 0.02 #0.02
    Kd: 0.3 #0.3
    setpoint: 0.001
    output_limits: [-0.7, 0.7]
  cfg_pid_angle:
    Kp: 4
    Ki: 0.01
    Kd: 0.01
    setpoint: 0
    output_limits: [-2, 2]
# det巡航pid
det_pid:
  cfg_pid_y:
    Kp: 0.3
    Ki: 0.01
    Kd: 0.005
    setpoint: 0
    output_limits: [-0.7, 0.7]
  cfg_pid_angle:
    Kp: 10
    Ki: 0.01
    Kd: 0.005
    setpoint: 0
    output_limits: [-0.7, 0.7]

# 定位pid参数
location_pid:
  pid_x:
    Kp: 0.5
    Ki: 0.01
    Kd: 0.005
    setpoint: 0
    output_limits: [-0.7, 0.7]
  pid_y:
    Kp: 1.2
    Ki: 0.01
    Kd: 0.005
    setpoint: 0
    output_limits: [-1.5, 1.5]
